"""Generate docs/state-machine.md from the LangGraph.

Run: cd backend && .venv/bin/python -m scripts.export_graph
"""

from pathlib import Path

from app.agent.graph import build_graph


def main() -> None:
    graph = build_graph()
    mermaid = graph.get_graph().draw_mermaid()
    out = Path(__file__).resolve().parent.parent.parent / "docs" / "state-machine.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# Twin agent state machine\n\n"
        "Generated by `backend/scripts/export_graph.py`.\n\n"
        "```mermaid\n"
        f"{mermaid}\n"
        "```\n"
    )
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
